version: "3.8"

services:
  bot:
    build: .
    container_name: telegram_insta_downloader
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./session:/app/session
